# Generated by Django 2.0.5 on 2019-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField(max_length=10)),
                ('question', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
