# Generated by Django 2.0.5 on 2019-04-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister_model',
            name='confirmpassword',
        ),
    ]
