# Generated by Django 2.0.5 on 2019-04-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_uploadmessage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
